# Site settings
title: J. Arturo Cocoma-Ortega
general_email: arturo.cocoma@gmail.com
academic_email: cocoma@inaoep.mx

description: > # this means to ignore newlines until "baseurl:"
  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://arturococoma.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: arturococoma
linkedin_username: arturo_cocoma
facebook_username: arturo_cocoma
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title